### ISSUE TITLE
Missing release artifacts for 1.61.1

### ISSUE THREAD

**Issue by radeksimko** [lightstep/terraform-provider-lightstep#89]
It appears the release artifacts are missing for the latest patch release: https://github.com/lightstep/terraform-provider-lightstep/releases

```hcl
terraform {
  required_providers {
    lightstep = {
      source = "lightstep/lightstep"
      version = "1.61.1"
    }
  }
}

provider "lightstep" {
  # Configuration options
}
```

```sh
terraform init
```
```
Initializing the backend...

Initializing provider plugins...
- Finding lightstep/lightstep versions matching "1.61.1"...
╷
│ Error: Failed to install provider
│
│ Error while installing lightstep/lightstep v1.61.1: could not query provider registry for registry.terraform.io/lightstep/lightstep: failed to retrieve
│ authentication checksums for provider: 404 Not Found
╵
```

**Comment by gdvalle** [comment]
Is this resolved now? Seems like they came in several hours later after this issue was opened: https://github.com/lightstep/terraform-provider-lightstep/releases/tag/v1.61.1
![image](https://user-images.githubusercontent.com/2582552/206568567-4bbc49e3-6b7d-4da9-933d-ed5e0e42ad25.png)

![image](https://user-images.githubusercontent.com/2582552/206568515-1c79c81e-1510-4634-8e08-8691ac0eecf9.png)
